import Head from 'next/head'
import Image from 'next/image'
import styles from '../assets/styles/Projects.module.scss'

export default function about() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <title>Projects - Jesse jansson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Take a look at all my projects
        </h1>
        <div className={styles.grid}>
          <a 
            rel="noreferrer"
            target="_blank"
            href="https://jessejansson.com/" 
            className={styles.card}>
            <h2>JesseJansson.com &rarr;</h2>
            <p>Find in-depth information about Jessejansson.</p>
          </a>

          <a 
            rel="noreferrer"
            target="_blank"
            href="https://cococurlsroom.nl/" 
            className={styles.card}>
            <h2>CocoCurlsRoom.nl &rarr;</h2>
            <p>CocoCurlsRoom, the CG barber located in Rotterdam.</p>
          </a>

          <a
            rel="noreferrer"
            target="_blank"
            href="https://janssonscooters.nl/"
            className={styles.card}
          >
            <h2>JanssonScooters.nl &rarr;</h2>
            <p>I like repairing mopeds too, this is my moped repair site.</p>
          </a>

          <a
            rel="noreferrer"
            target="_blank"
            href="https://jessejansson.com/contact"
            className={styles.card}
          >
            <h2>More coming... &rarr;</h2>
            <p>Maybe your next website will be in this section.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
